# Generated by Django 5.1.4 on 2024-12-15 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0003_book_fee_alter_libraryhistory_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeshistory',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_history_amount', related_query_name='fees_history_amount', to='LibApp.fee'),
        ),
        migrations.AlterField(
            model_name='feeshistory',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_history_fee_type', related_query_name='fees_history_fee_type', to='LibApp.fee'),
        ),
    ]
