# Generated by Django 5.1.4 on 2024-12-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0004_alter_feeshistory_amount_alter_feeshistory_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeshistory',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
